spring.application.name=config-manager

# ===============================
# PostgreSQL Database Connection
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/noreboot_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Kafka Configuration
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=config-service-group
